### ISSUE TITLE
Algorithm implementation details

### ISSUE THREAD

**Issue by srikanthmalla** [xk-huang/yet-another-vectornet#22]
Hi @xk-huang ,
I have two questions regarding the algorithm implementation:
1. Do you do concatenation of max pool to the MLP feature in the subgraph? It looks like that is not implemented.
2. Is there an auxiliary loss for graph completion similar to the paper?

Please let me know if you plan to add those or if you tried similar experiments?

Thank you,
Srikanth

**Comment by xk-huang** [comment]
Hi @srikanthmalla! Sorry to reply so late. Currently, there is no plan to complete the codebase, specifically the graph completion module due to the switch of my research area.
Advanced works like TNT or DenseTNT are also worth checking out.
