### ISSUE TITLE
Velocity Calculation for obstacles

### ISSUE THREAD

**Issue by purewater0901** [xk-huang/yet-another-vectornet#27]
Hello. Thank you for sharing your codes with us, and this repo helps me a lot to understand the original paper. When I read your code, I found that the velocity calculation [here](https://github.com/xk-huang/yet-another-vectornet/blob/master/utils/object_utils.py#L28-L33) might not be appropriate. I think this part should be

```
vel_x, vel_y = zip(*[((x_coord[i] - x_coord[i - 1]) / (float(timestamp[i]) - float(timestamp[i - 1])),
                      (y_coord[i] - y_coord[i - 1]) / (float(timestamp[i]) - float(timestamp[i - 1])),) for i in range(1, len(timestamp))])
```
(I guess you might have to add () in `x_coord[i] - x_coord[i - 1])` and `y_coord[i] - y_coord[i - 1]`). I think this would not cause serious issues to your final results(since the velocity becomes pretty fast in your code, your dataset does not remove static obstacles), but hope this issue will help you and others.

**Comment by xk-huang** [comment]
Thank you so much for pointing out my mistake!
