### ISSUE TITLE
[Bug-Report] ’list‘ object has no attribute 'time_step_len'

### ISSUE THREAD

**Issue by littleDrew** [xk-huang/yet-another-vectornet#28]
Hi buddy,
    here i run the training script `train.py` and found **error raised like follows**:

  ```Shell
  Traceback (most recent call last):
      File "train.py", line 113 in <module>
          out = model(data)
      File "data1/env/test38/lib/python3.8/site-package/torch/nn/modules/module.py", line 727, in _call_impl
          result = self.forward(*input, *kwargs)
      File "home/test38/[yet-another-vectornet/modeling/vectornet.py", in line 52, in forward
          time_step_len = int(data.time_step_len[0])
  AttributeError:  ’list‘ object has no attribute 'time_step_len'
  ```
Here i check the input `data` of modle, it is a list of GraphData, like follows, which result unable to access `data.time_step_len` directly like above:

  ```python
  [GraphData(cluster=[259], edge_index=[2, 2939], time_step_len=[1], valid_len=[1], x=[259, 8], y=[60]),
    ...     
   GraphData(cluster=[157], edge_index=[2, 1370], time_step_len=[1], valid_len=[1], x=[157, 8], y=[60]
  ```
- https://github.com/xk-huang/yet-another-vectornet/blob/master/train.py#L110
- https://github.com/xk-huang/yet-another-vectornet/blob/master/modeling/vectornet.py#L52
> here refered:   data (Data): [x, y, cluster, edge_index, valid_len]
> but after batch the data is a batch of data list, seems not match

**should the `Net` been modified or batch_size can only be 1 and sequeese the outer dimension in advance?**
Waitting for you explanation, thanks~   @xk-huang

**Comment by HanZheng777** [comment]
Hi, 

I think you are not using the DataParallel module from torch_geometric.nn but directly from torch.nn. Please follow the document on [https://pytorch-geometric.readthedocs.io/en/latest/modules/loader.html#torch_geometric.loader.DataListLoader](url) where the DataListLoader should be used together with torch_geometric.nn.DataParallel.

Thanks

**Comment by yuxinl915** [comment]
Hi Zheng Han,

Really appreciate your giving assistance to us! I also got similar problems when I ran train.py, but it only got a segmentation fault due to an instance of 'std: :bad_alloc'. I noticed that this problem began to take place at line 84, after we read in data for training and validation, and passed to DataListLoader. What might be the possible reason for it? Appreciate any help you can provide!

Best,
Yuxin
