### ISSUE TITLE
About Constructing Data and Intermediate Data

### ISSUE THREAD

**Issue by yuxinl915** [xk-huang/yet-another-vectornet#30]
Dear xk-huang,

Thanks so much for providing this! Your implementation is wonderful! However, I still got one question when I completed the preparation before training the models. In README.md, Usage, Step 1 and Step 2, you suggested that we could download the prepared dataset objects and put them in ./data. However, I could only find intermediate_data in the Google Drive you provided. In utils/config.py, I noticed that DATA_DIR and INTERMEDIATE_DATA_DIR were different, which, I guessed, indicated that I might need to download more files. More specifically, as you mentioned train/val/test, which should be placed in ./data, I just couldn't find them in your Google Drive. Did I make anything wrong? Could you please give me some advice? Appreciate any help you can provide!

**Comment by CeFf1z** [comment]
I have downloaded the INTERMEDIATE_DATA from Google Drive.There is _train_data = GraphDataset(TRAIN_DIR)_ from _'train.py'_,which i can't run successfully.How did you solve this problem with .pkl file reading.
