### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by Lewis-Lu** [xk-huang/yet-another-vectornet#31]
The items in the requirement.txt, most of them are unnecessary, confused me when I install them until I opened the file. 

In master branch, I suppose the following requirements are enough.

matplotlib==3.1.1
numpy==1.18.1
numpy-quaternion==2020.5.19.15.27.24
numpydoc==0.9.2
pandas==1.0.0
torch==1.4.0
torch-cluster==1.5.4
torch-geometric==1.5.0
torch-scatter==2.0.4
torch-sparse==0.6.1
torch-spline-conv==1.2.0
torchvision==0.5.0
tqdm==4.42.0
-e git+https://github.com/argoai/argoverse-api.git@c81d9375d86acf57433d528ca7e8b589d5700487#egg=argoverse

**Comment by xk-huang** [comment]
Thanks for your sharing! I believe it helps a lot for other!
