### ISSUE TITLE
Some question about the result?

### ISSUE THREAD

**Issue by wanglaotou** [xk-huang/yet-another-vectornet#33]
hi, great work, as you showed in the repo, i see the result without lanes, does it mean training this model do not need hd-maps?
![image](https://user-images.githubusercontent.com/12837585/205013154-a1bba3b0-5d4c-424e-8550-c4f481e8ed15.png)

**Comment by Zz512910116** [comment]
Excuse me, do you know? I also want to ask this question.

**Comment by MichaelH717** [comment]
@wanglaotou 请问你有报这个错误吗？
![image](https://user-images.githubusercontent.com/75190093/230562117-f4af8a9b-f305-4515-9392-20d70823189a.png)

**Comment by wanglaotou** [comment]
> @wanglaotou 请问你有报这个错误吗？ ![image](https://user-images.githubusercontent.com/75190093/230562117-f4af8a9b-f305-4515-9392-20d70823189a.png)

hi, it seems that your python version or torch version does not match, you can follow the requirements in the readme.md.

**Comment by MichaelH717** [comment]
> > @wanglaotou 请问你有报这个错误吗？ ![image](https://user-images.githubusercontent.com/75190093/230562117-f4af8a9b-f305-4515-9392-20d70823189a.png)
> 
> hi, it seems that your python version or torch version does not match, you can follow the requirements in the readme.md.

hi, which python version are you using? it not work for me to follow the requirements in the readme.md, thanks a lot

**Comment by MichaelH717** [comment]
> > @wanglaotou 请问你有报这个错误吗？ ![image](https://user-images.githubusercontent.com/75190093/230562117-f4af8a9b-f305-4515-9392-20d70823189a.png)
> 
> hi, it seems that your python version or torch version does not match, you can follow the requirements in the readme.md.

**Comment by ItsPeter999** [comment]
> 没有呢。。 张震 ***@***.*** 重庆大学 研究生 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xk-huang/yet-another-vectornet" ***@***.***&gt;; 发送时间:&nbsp;2023年4月7日(星期五) 下午3:22 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xk-huang/yet-another-vectornet] Some question about the result? (Issue #33) @wanglaotou 请问你有报这个错误吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

同学你是重大的吗，能加个微信交流一下吗，我也是重大的。

**Comment by waiyu0305** [comment]
> @wanglaotou 请问你有报这个错误吗？ ![image](https://user-images.githubusercontent.com/75190093/230562117-f4af8a9b-f305-4515-9392-20d70823189a.png)

Maybe you can try to modify the inc of GraphData in the dataset.py file, add "store" and try again
![图片](https://github.com/xk-huang/yet-another-vectornet/assets/125355889/28f237f4-1383-468f-8fb7-651c0bb5b307)

**Comment by MichaelH717** [comment]
> > @wanglaotou 请问你有报这个错误吗？ ![image](https://user-images.githubusercontent.com/75190093/230562117-f4af8a9b-f305-4515-9392-20d70823189a.png)
> 
> Maybe you can try to modify the inc of GraphData in the dataset.py file, add "store" and try again ![图片](https://private-user-images.githubusercontent.com/125355889/239185505-28f237f4-1383-468f-8fb7-651c0bb5b307.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDM5ODEsIm5iZiI6MTcwMzYwMzY4MSwicGF0aCI6Ii8xMjUzNTU4ODkvMjM5MTg1NTA1LTI4ZjIzN2Y0LTEzODMtNDY4Zi04ZmI3LTY1MWMwYmI1YjMwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxNTE0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGRkY2ZiNTdkNGU3YzU2M2U3MDcwODM4ZmFmYzk3MjFlYTQ0YjRhZTQxNzQyNWNiYzA4ZjRmZmY1MDY2YzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HbJober0fRUozwP7Ju6-hcLBiLLGW_RGYLJnwCDue_c)

thanks alot
