### ISSUE TITLE
Some hint

### ISSUE THREAD

**Issue by uchihatmtkinu** [xk-huang/yet-another-vectornet#7]
Hi，I am also trying to implement the vectornet and notice you are in some trouble. Maybe I can share you something.

My implementation is not perfect, but I still achieve some progress. 
From the leaderboard, the ID of "tmtkinu" is the version of "Map" from the paper which has ADE(k=1)=1.92m and FDE(k=1)=4.3m. The ID of "miaomiao" is the version of "none" which has ADE(k=1)=2.20m and FDE(k=1)=5.05m.

It seems that the output should be the offset of the traj rather than the absolute position, in which the predicted traj would be more reasonable.

**Comment by xk-huang** [comment]
Thanks for your advice :)
I have already use the offset representation. The real problem of my implementation is that I massed up with the input data: 
```
polyline_features: vstack[
        (xs, ys, xe, ye, timestamp, NULL, NULL, polyline_id),
        (xs, ys, xe, ye, NULL, zs, ze, polyline_id)
]
```
The authors informed that they only used centerline information with the Argoverse dataset. So maybe (x, y) coordinates with additional centerlines are enough?

**Comment by uchihatmtkinu** [comment]
Is that true that the vectornet authors said they just used the centerlines? I don't know that. 

For the none(just one polyline of agent traj) setting, I use the pure data format of [x1, y1, x2, y2, 0, 0] which could achieve the perfomance mentioned above. Maybe there are something else that infer your result. Maybe we can discuss in wechat?

**Comment by minrui-hust** [comment]
@xk-huang 作者说只用到了中心线的出处在哪？

**Comment by iyuner** [comment]
From the paper, the authors mentioned they included lane boundaries in the HD map feature, e.g "a lane boundary contains multiple control points that build a spline". So maybe not centerline?

**Comment by xk-huang** [comment]
Hi @iyuner, sorry for being late on some DDLs!
Here is the reply from the author explained why use centerline: as in Argoverse, only lane centers are provided :)
![Uploading Screenshot from 2020-07-29 13-39-57.png…](author's reply)
